# audio_profiles.py
"""Per-model audio processing configuration profiles."""

PROFILES = {
    "xtts": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 500,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 22050,
    },
    "fish": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -40,
        "min_silence_ms": 400,
        "front_protect_ms": 80,
        "end_protect_ms": 600,
        "inter_pause_sec": 0.2,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "kokoro": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -40,
        "min_silence_ms": 300,
        "front_protect_ms": 250,
        "end_protect_ms": 1100,
        "inter_pause_sec": 0.3,
        "front_pad_sec": 0.15,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "bark": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 500,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.2,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
        "history_reset_every": 5,
    },
    "chatterbox": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "f5": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -40,
        "min_silence_ms": 400,
        "front_protect_ms": 80,
        "end_protect_ms": 600,
        "inter_pause_sec": 0.15,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "dia": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 44100,
    },
    "qwen": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "vibevoice": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "higgs": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
}

TEXT_LIMITS = {
    "xtts": 250,
    "fish": 250,
    "kokoro": 500,
    "bark": 200,
    "chatterbox": 250,
    "f5": 135,
    "dia": 400,
    "qwen": 300,
    "vibevoice": 300,
    "higgs": 300,
    "default": 300,
}
